### PR TITLE
Replacing BrowserRouter with HashRouter for github pages deployment

### PR DESCRIPTION
**Pull request by keyboardbreaker**
Also includes github pages dev dependencies.

### CODE REVIEW

**Comment by keyboardbreaker** [comment]
Deployed to my [fork](https://keyboardbreaker.github.io/seasonal-cuisine/)

Shall deploy to kodiri master when we have completed the final filter functionality.

**Review by MartaBekyarska — APPROVED** [review]
Looks good! 👍

**Review by MartaBekyarska — APPROVED** [review]
👍

**Comment by keyboardbreaker** [comment]
thanks!

**Pull request merged**
