### PR TITLE
create placeholder for the dropdown

### PR DESCRIPTION
**Pull request by alexandra-pascal**
Created the placeholder for the drop down
- on mobile version the placeholder doesn't cover the recipes
- on desktop the placeholder is positioned correctly  under the text

### CODE REVIEW

**Comment by keyboardbreaker** [comment]
reviewing

**Comment by keyboardbreaker** [comment]
Hi, this is the white box you showed me today, right?

also why have you over populated the home component with divs?

**Comment by alexandra-pascal** [comment]
Yes, it's only the placeholder

**Comment by keyboardbreaker** [comment]
those divs are padding the placeholder?

**Comment by alexandra-pascal** [comment]
check phone for pics

**Review by keyboardbreaker — CHANGES_REQUESTED** [review]
remove the repeated divs in the home component

**Review by keyboardbreaker — APPROVED** [review]
Looks much better, approving.

**Pull request merged**
